DELETE http://localhost:3001/api/v1/blogs/1

###
DELETE http://localhost:3001/api/v1/blogs/62c9d6d3cfb0e98bb430d4b9
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impva2VyaW55YSIsImlkIjoiNjJjOWNmNjAzMzE5MjUzYWZmOWVmN2E5IiwiaWF0IjoxNjU3Mzk0ODg2LCJleHAiOjE2NTk5ODY4ODZ9.InZgDAFMylimGOV9n8iDPRIvYYbFNiMP7h6Uzh0nQxU