POST http://localhost:3001/api/v1/login
Content-Type: application/json

{
    "username": "jokerinya",
    "name": "Ibrahim Sakaci",
    "password": "secretsecret"
}

###
POST http://localhost:3001/api/v1/login
Content-Type: application/json

{
    "username": "hellas",
    "name": "Arto Hellas",
    "password": "salainen"
}